/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as toolsWatermarkPdfRouteImport } from './routes/(tools)/watermark-pdf'
import { Route as toolsSplitPdfRouteImport } from './routes/(tools)/split-pdf'
import { Route as toolsRotatePdfRouteImport } from './routes/(tools)/rotate-pdf'
import { Route as toolsReorganizePdfRouteImport } from './routes/(tools)/reorganize-pdf'
import { Route as toolsMetadataEditorRouteImport } from './routes/(tools)/metadata-editor'
import { Route as toolsMergePdfRouteImport } from './routes/(tools)/merge-pdf'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsWatermarkPdfRoute = toolsWatermarkPdfRouteImport.update({
  id: '/(tools)/watermark-pdf',
  path: '/watermark-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsSplitPdfRoute = toolsSplitPdfRouteImport.update({
  id: '/(tools)/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsRotatePdfRoute = toolsRotatePdfRouteImport.update({
  id: '/(tools)/rotate-pdf',
  path: '/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsReorganizePdfRoute = toolsReorganizePdfRouteImport.update({
  id: '/(tools)/reorganize-pdf',
  path: '/reorganize-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsMetadataEditorRoute = toolsMetadataEditorRouteImport.update({
  id: '/(tools)/metadata-editor',
  path: '/metadata-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsMergePdfRoute = toolsMergePdfRouteImport.update({
  id: '/(tools)/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/merge-pdf': typeof toolsMergePdfRoute
  '/metadata-editor': typeof toolsMetadataEditorRoute
  '/reorganize-pdf': typeof toolsReorganizePdfRoute
  '/rotate-pdf': typeof toolsRotatePdfRoute
  '/split-pdf': typeof toolsSplitPdfRoute
  '/watermark-pdf': typeof toolsWatermarkPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/merge-pdf': typeof toolsMergePdfRoute
  '/metadata-editor': typeof toolsMetadataEditorRoute
  '/reorganize-pdf': typeof toolsReorganizePdfRoute
  '/rotate-pdf': typeof toolsRotatePdfRoute
  '/split-pdf': typeof toolsSplitPdfRoute
  '/watermark-pdf': typeof toolsWatermarkPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/(tools)/merge-pdf': typeof toolsMergePdfRoute
  '/(tools)/metadata-editor': typeof toolsMetadataEditorRoute
  '/(tools)/reorganize-pdf': typeof toolsReorganizePdfRoute
  '/(tools)/rotate-pdf': typeof toolsRotatePdfRoute
  '/(tools)/split-pdf': typeof toolsSplitPdfRoute
  '/(tools)/watermark-pdf': typeof toolsWatermarkPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/merge-pdf'
    | '/metadata-editor'
    | '/reorganize-pdf'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/watermark-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/merge-pdf'
    | '/metadata-editor'
    | '/reorganize-pdf'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/watermark-pdf'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/(tools)/merge-pdf'
    | '/(tools)/metadata-editor'
    | '/(tools)/reorganize-pdf'
    | '/(tools)/rotate-pdf'
    | '/(tools)/split-pdf'
    | '/(tools)/watermark-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  toolsMergePdfRoute: typeof toolsMergePdfRoute
  toolsMetadataEditorRoute: typeof toolsMetadataEditorRoute
  toolsReorganizePdfRoute: typeof toolsReorganizePdfRoute
  toolsRotatePdfRoute: typeof toolsRotatePdfRoute
  toolsSplitPdfRoute: typeof toolsSplitPdfRoute
  toolsWatermarkPdfRoute: typeof toolsWatermarkPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/watermark-pdf': {
      id: '/(tools)/watermark-pdf'
      path: '/watermark-pdf'
      fullPath: '/watermark-pdf'
      preLoaderRoute: typeof toolsWatermarkPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/split-pdf': {
      id: '/(tools)/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof toolsSplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/rotate-pdf': {
      id: '/(tools)/rotate-pdf'
      path: '/rotate-pdf'
      fullPath: '/rotate-pdf'
      preLoaderRoute: typeof toolsRotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/reorganize-pdf': {
      id: '/(tools)/reorganize-pdf'
      path: '/reorganize-pdf'
      fullPath: '/reorganize-pdf'
      preLoaderRoute: typeof toolsReorganizePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/metadata-editor': {
      id: '/(tools)/metadata-editor'
      path: '/metadata-editor'
      fullPath: '/metadata-editor'
      preLoaderRoute: typeof toolsMetadataEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/merge-pdf': {
      id: '/(tools)/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof toolsMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  toolsMergePdfRoute: toolsMergePdfRoute,
  toolsMetadataEditorRoute: toolsMetadataEditorRoute,
  toolsReorganizePdfRoute: toolsReorganizePdfRoute,
  toolsRotatePdfRoute: toolsRotatePdfRoute,
  toolsSplitPdfRoute: toolsSplitPdfRoute,
  toolsWatermarkPdfRoute: toolsWatermarkPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
