/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as ReorganizePdfRouteImport } from './routes/reorganize-pdf'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MetadataEditorRouteImport } from './routes/metadata-editor'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as IndexRouteImport } from './routes/index'

const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ReorganizePdfRoute = ReorganizePdfRouteImport.update({
  id: '/reorganize-pdf',
  path: '/reorganize-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataEditorRoute = MetadataEditorRouteImport.update({
  id: '/metadata-editor',
  path: '/metadata-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merge-pdf': typeof MergePdfRoute
  '/metadata-editor': typeof MetadataEditorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reorganize-pdf': typeof ReorganizePdfRoute
  '/split-pdf': typeof SplitPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merge-pdf': typeof MergePdfRoute
  '/metadata-editor': typeof MetadataEditorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reorganize-pdf': typeof ReorganizePdfRoute
  '/split-pdf': typeof SplitPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merge-pdf': typeof MergePdfRoute
  '/metadata-editor': typeof MetadataEditorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reorganize-pdf': typeof ReorganizePdfRoute
  '/split-pdf': typeof SplitPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merge-pdf'
    | '/metadata-editor'
    | '/privacy-policy'
    | '/reorganize-pdf'
    | '/split-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merge-pdf'
    | '/metadata-editor'
    | '/privacy-policy'
    | '/reorganize-pdf'
    | '/split-pdf'
  id:
    | '__root__'
    | '/'
    | '/merge-pdf'
    | '/metadata-editor'
    | '/privacy-policy'
    | '/reorganize-pdf'
    | '/split-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MergePdfRoute: typeof MergePdfRoute
  MetadataEditorRoute: typeof MetadataEditorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReorganizePdfRoute: typeof ReorganizePdfRoute
  SplitPdfRoute: typeof SplitPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reorganize-pdf': {
      id: '/reorganize-pdf'
      path: '/reorganize-pdf'
      fullPath: '/reorganize-pdf'
      preLoaderRoute: typeof ReorganizePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata-editor': {
      id: '/metadata-editor'
      path: '/metadata-editor'
      fullPath: '/metadata-editor'
      preLoaderRoute: typeof MetadataEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MergePdfRoute: MergePdfRoute,
  MetadataEditorRoute: MetadataEditorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReorganizePdfRoute: ReorganizePdfRoute,
  SplitPdfRoute: SplitPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
